---
title: 5p2p 2.0
timezone: UTC
collections:
  drafts:
    title: Drafts
    output: false
  posts:
    title: Posts
    output: true
  static_content:
    title: Static content
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
    summary: 
- scope:
    path: ''
    type: post
  values:
    layout: post
    author: ''
    summary: ''
- scope:
    path: ''
    type: drafts
  values:
    layout: post
    author: ''
    summary: ''
drafts: true
