---
title: 5p2p 2.0
timezone: UTC
collections:
  drafts:
    title: Drafts
    output: true
  posts:
    title: Posts
    output: true
  static_content:
    title: Static content
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: test
    author: Ruvido
