---
title: 5p2p 2.0
timezone: UTC
collections:
  my_pages:
    title: My pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: post
  values:
    layout: post
    author: ''
    summary: ''
    image: 
    links: []
